# Configure file for ChatBridgeReforged
# Check https://github.com/R1ckyH/ChatBridgeReforged for detail
# Don't be Surprised, I just edit from [MCDR](https://github.com/Fallen-Breath/MCDReforged)


# =========================================
# |            Basic Configure            |
# =========================================


# Server setting
# The ip_address, port and aes_key that CBR use
server_setting:
  host_name: '127.0.0.1'
  port: 30001
  aes_key: 'ThisIsTheSecret'


# Client_servers setting
# A List for server servers
clients:
  - name: 'survival'
    password: 'survival'
  - name: 'cqhttp'
    password: 'cqhttp'


# The language that CBR will use to display information
# Examples: "en_us", "zh_cn"
# Not available now


# =========================================
# |           Advance Configure           |
# =========================================


# Debug mode switches
# Size(kb) that CBR zip the logs after the logger files more than 'size_to_zip' (default 1024)
# set to 0 to create zip everytime when CBR start
# When start up, CBR will zip the log if necessary
# split log is split the log into latest.log and chat.log (chat including the log of plugin output to console)
log:
  size_to_zip: 1024
  split_log: true
  size_to_zip_chat: 1024


# Debug mode switches
debug:
  all: false
  CBR: false
  plugin: false
